name: Convert .ipynb to .py

on:
  push:
    branches:
      - test  # Trigger the workflow on pushes to the 'test' branch

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: test  # Check out the 'test' branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Find and convert .ipynb files
      run: |
        for notebook in $(find . -name "*.ipynb"); do
          jupyter nbconvert --to script "$notebook"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Convert .ipynb files to .py"
        git push https://x-access-token:${{ secrets.PYCONVERT }}@github.com/yarshilshah/Databricks.git test  # Push to the 'test' branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
